/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.69
 * Generated at: 2021-09-15 10:12:46 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("<script src=\"https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js\"></script>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("	");
      out.write("\r\n");
      out.write("\r\n");
      out.write("	<h1 align=\"center\">JQuery를 이용한 Ajax 테스트</h1>\r\n");
      out.write("	<h3>1. 버튼 클릭시 get 방식으로 서버 데이터 전송 및 응답</h3>\r\n");
      out.write("	\r\n");
      out.write("	입력 : \r\n");
      out.write("	<input type = \"text\" id=\"input1\">\r\n");
      out.write("	<button id=\"btn1\">전송</button><br><br>\r\n");
      out.write("	\r\n");
      out.write("	응답 : \r\n");
      out.write("	<input type = \"text\" id=\"output1\" style=\"width:300px\" readonly>\r\n");
      out.write("	\r\n");
      out.write("	<script>\r\n");
      out.write("	$(function() {\r\n");
      out.write("		//1. 버튼 클릭시 get 방식으로 서버 데이터 전송 및 응답\r\n");
      out.write("		$(\"#btn1\").click(function(){\r\n");
      out.write("			var input = $(\"#input1\").val();\r\n");
      out.write("			$.ajax({\r\n");
      out.write("				\r\n");
      out.write("				//url : 데이터를 전송할 url(필수 요소)\r\n");
      out.write("				url : \"jqTest1.do\",\r\n");
      out.write("				\r\n");
      out.write("				//data : 요청 시 전달할 파라미터 설정\r\n");
      out.write("				data : {\r\n");
      out.write("					input : input\r\n");
      out.write("				},\r\n");
      out.write("				\r\n");
      out.write("				//type : 전송할 방식 (get, post)\r\n");
      out.write("				type : \"get\",\r\n");
      out.write("				\r\n");
      out.write("				//success : ajax 통신 성공 시 처리할 함수 지정\r\n");
      out.write("				success : function(result){\r\n");
      out.write("					console.log(\"ajax 통신 성공\");\r\n");
      out.write("					$(\"#output1\").val(result);\r\n");
      out.write("				},\r\n");
      out.write("				\r\n");
      out.write("				//error : 통신 실패시 처리할 함수 지정\r\n");
      out.write("				error : function() {\r\n");
      out.write("					console.log(\"ajax 통신 실패\");\r\n");
      out.write("				},\r\n");
      out.write("				\r\n");
      out.write("				//complete : 통신 여부와 상관 없이 실행\r\n");
      out.write("				complete : function(){\r\n");
      out.write("					console.log(\"무조건 호출\");\r\n");
      out.write("				}\r\n");
      out.write("			})\r\n");
      out.write("		})\r\n");
      out.write("	})\r\n");
      out.write("	</script>\r\n");
      out.write("	\r\n");
      out.write("	<h3>2. 버튼 클릭시 post 방식으로 서버 데이터 전송 및 응답</h3>\r\n");
      out.write("	\r\n");
      out.write("	입력 : \r\n");
      out.write("	<input type = \"text\" id=\"input2\">\r\n");
      out.write("	<button id=\"btn2\">전송</button><br><br>\r\n");
      out.write("	\r\n");
      out.write("	응답 : \r\n");
      out.write("	<input type = \"text\" id=\"output2\" style=\"width:300px\" readonly>\r\n");
      out.write("	\r\n");
      out.write("	<script>\r\n");
      out.write("	$(function() {\r\n");
      out.write("		//2. 버튼 클릭시 post 방식으로 서버 데이터 전송 및 응답\r\n");
      out.write("		$(\"#btn2\").click(function(){\r\n");
      out.write("			var input = $(\"#input2\").val();\r\n");
      out.write("			$.ajax({\r\n");
      out.write("				\r\n");
      out.write("				//url : 데이터를 전송할 url(필수 요소)\r\n");
      out.write("				url : \"jqTest2.do\",\r\n");
      out.write("				\r\n");
      out.write("				//data : 요청 시 전달할 파라미터 설정\r\n");
      out.write("				data : {\r\n");
      out.write("					input : input\r\n");
      out.write("				},\r\n");
      out.write("				\r\n");
      out.write("				//type : 전송할 방식 (get, post)\r\n");
      out.write("				type : \"post\",\r\n");
      out.write("				\r\n");
      out.write("				//success : ajax 통신 성공 시 처리할 함수 지정\r\n");
      out.write("				success : function(result){\r\n");
      out.write("					console.log(\"ajax 통신 성공\");\r\n");
      out.write("					$(\"#output2\").val(result);\r\n");
      out.write("				},\r\n");
      out.write("				\r\n");
      out.write("				//error : 통신 실패시 처리할 함수 지정\r\n");
      out.write("				error : function(e) {\r\n");
      out.write("					console.log(e);\r\n");
      out.write("					console.log(\"ajax 통신 실패\");\r\n");
      out.write("				}\r\n");
      out.write("				\r\n");
      out.write("			})\r\n");
      out.write("		})\r\n");
      out.write("	})\r\n");
      out.write("	</script>\r\n");
      out.write("	\r\n");
      out.write("	<h3>3. 버튼 클릭시 post 방식으로 여러 개의 데이터 전송 및 응답</h3>\r\n");
      out.write("	\r\n");
      out.write("	이릅 : <input type = \"text\" id=\"input3_1\">\r\n");
      out.write("	나이 : <input type = \"text\" id=\"input3_2\">\r\n");
      out.write("	<button id=\"btn3\">전송</button><br><br>\r\n");
      out.write("	\r\n");
      out.write("	응답 : \r\n");
      out.write("	<input type = \"text\" id=\"output3\" style=\"width:300px\" readonly>\r\n");
      out.write("	\r\n");
      out.write("	<script>\r\n");
      out.write("	$(function() {\r\n");
      out.write("		\r\n");
      out.write("		$(\"#btn3\").click(function(){\r\n");
      out.write("			var input3_1 = $(\"#input3_1\").val();\r\n");
      out.write("			var input3_2 = $(\"#input3_2\").val();\r\n");
      out.write("			$.ajax({\r\n");
      out.write("				\r\n");
      out.write("				url : \"jqTest3.do\",\r\n");
      out.write("		\r\n");
      out.write("				data : {\r\n");
      out.write("					name : input3_1,\r\n");
      out.write("					age : input3_2\r\n");
      out.write("				},\r\n");
      out.write("				\r\n");
      out.write("				type : \"post\",\r\n");
      out.write("				\r\n");
      out.write("				success : function(result){\r\n");
      out.write("					console.log(\"ajax 통신 성공\");\r\n");
      out.write("					$(\"#output3\").val(result);\r\n");
      out.write("				},\r\n");
      out.write("				\r\n");
      out.write("				error : function() {\r\n");
      out.write("					console.log(\"ajax 통신 실패\");\r\n");
      out.write("				}\r\n");
      out.write("				\r\n");
      out.write("			})\r\n");
      out.write("		})\r\n");
      out.write("	})\r\n");
      out.write("	</script>\r\n");
      out.write("	\r\n");
      out.write("	<h3>4. 서버로 기본형 데이터 전송 후 , 응답 객체를 (object) 받기</h3>\r\n");
      out.write("	\r\n");
      out.write("	회원번호 입력 : <input type = \"text\" id=\"input4\">\r\n");
      out.write("	<button id=\"btn4\">전송</button><br><br>\r\n");
      out.write("	<textarea id=\"textArea4\" rows=\"4\" cols=\"30\"></textarea>\r\n");
      out.write("	\r\n");
      out.write("	<script>\r\n");
      out.write("	$(function() {\r\n");
      out.write("		\r\n");
      out.write("		$(\"#btn4\").click(function(){\r\n");
      out.write("			var input = $(\"#input4\").val();\r\n");
      out.write("			\r\n");
      out.write("			$.ajax({\r\n");
      out.write("				\r\n");
      out.write("				url : \"jqTest4.do\",\r\n");
      out.write("		\r\n");
      out.write("				data : {\r\n");
      out.write("					input : input\r\n");
      out.write("				},\r\n");
      out.write("				\r\n");
      out.write("				type : \"get\",\r\n");
      out.write("				dataType:\"json\",\r\n");
      out.write("				\r\n");
      out.write("				success : function(obj){\r\n");
      out.write("					console.log(obj);\r\n");
      out.write("					var result = \"\";\r\n");
      out.write("					\r\n");
      out.write("					if(obj != null){\r\n");
      out.write("						result = \"번호 : \"+ obj.no + \"\\n\"\r\n");
      out.write("							   + \"이름 : \"+ obj.name + \"\\n\"\r\n");
      out.write("							   + \"나이 : \"+ obj.age + \"\\n\"\r\n");
      out.write("							   + \"성별 : \"+ obj.gender;\r\n");
      out.write("					}else{\r\n");
      out.write("						result = \"사용자 정보가 없습니다.\"\r\n");
      out.write("					}\r\n");
      out.write("					\r\n");
      out.write("					$(\"#textArea4\").val(result);\r\n");
      out.write("					\r\n");
      out.write("				},\r\n");
      out.write("				\r\n");
      out.write("				error : function(e) {					\r\n");
      out.write("					$(\"#textArea4\").val(\"ajax 통신 실패\");\r\n");
      out.write("				}\r\n");
      out.write("				\r\n");
      out.write("			})\r\n");
      out.write("			\r\n");
      out.write("		})\r\n");
      out.write("	})\r\n");
      out.write("	</script>	\r\n");
      out.write("	\r\n");
      out.write("	<h3>5. 서버로 기본형 데이터 전송 후 , 응답을 리스트 형태로 받기</h3>\r\n");
      out.write("	<h4>선택한 성별을 가진 모든 회원정보를 가지고 오기</h4>\r\n");
      out.write("	성별 :\r\n");
      out.write("	남 <input type = \"radio\" name=\"chk_gender5\" value =\"남\" checked>\r\n");
      out.write("	여 <input type = \"radio\" name=\"chk_gender5\" value =\"여\" >\r\n");
      out.write("	<button id=\"btn5\">전송</button><br><br>\r\n");
      out.write("	<textarea id=\"textArea5\" rows=\"4\" cols=\"30\"></textarea>\r\n");
      out.write("	\r\n");
      out.write("	<script>\r\n");
      out.write("	$(function() {\r\n");
      out.write("		$(\"#btn5\").click(function(){\r\n");
      out.write("			var gen = $('input[name=\"chk_gender5\"]:checked').val();\r\n");
      out.write("			\r\n");
      out.write("			console.log(\"gen : \"+gen);\r\n");
      out.write("			$.ajax({\r\n");
      out.write("				url :\"jqTest5.do\",\r\n");
      out.write("				data : {\r\n");
      out.write("					gender:gen\r\n");
      out.write("				},\r\n");
      out.write("				type:\"get\",\r\n");
      out.write("				success:function(list){\r\n");
      out.write("					console.log(list);\r\n");
      out.write("					var result=\"\";\r\n");
      out.write("					$.each(list, function(i){\r\n");
      out.write("						result +=list[i].no+\" / \"\r\n");
      out.write("								+ list[i].name + \" / \"\r\n");
      out.write("								+ list[i].age + \" / \"\r\n");
      out.write("								+ list[i].gender + \" \\n \"\r\n");
      out.write("					})\r\n");
      out.write("					$(\"#textArea5\").val(result)\r\n");
      out.write("				},\r\n");
      out.write("				error:function(e){\r\n");
      out.write("					$(\"#textArea5\").val(\"ajax 통신 실패\")\r\n");
      out.write("				}\r\n");
      out.write("			})\r\n");
      out.write("			\r\n");
      out.write("		})\r\n");
      out.write("	})\r\n");
      out.write("	</script>\r\n");
      out.write("	\r\n");
      out.write("	<h3>6.서버로 데이터 전송후 , 응답을 맵(map)형태로 받아서 테이블에 출력하기</h3>\r\n");
      out.write("	<h4>조회하고자 하는 회원의 이름 키워드를 입력해서 조회되는 회원들 정보와 전달된 키워드를 받아오기 </h4>\r\n");
      out.write("	\r\n");
      out.write("	\r\n");
      out.write("	이름<input type=\"text\" id = \"input6\" width=300>\r\n");
      out.write("	<button id = \"btn6\">검색</button>\r\n");
      out.write("	<table id = \"memberTable6\" border =\"1\" style=\"text-align:center\">\r\n");
      out.write("		<thead>\r\n");
      out.write("			<th>번호</th>\r\n");
      out.write("			<th>이름</th>\r\n");
      out.write("			<th>나이</th>\r\n");
      out.write("			<th>성별</th>\r\n");
      out.write("		</thead>\r\n");
      out.write("		<tbody>\r\n");
      out.write("		\r\n");
      out.write("		</tbody>\r\n");
      out.write("	\r\n");
      out.write("	\r\n");
      out.write("	</table>\r\n");
      out.write("	\r\n");
      out.write("	<script>\r\n");
      out.write("		$(function(){\r\n");
      out.write("			$(\"#btn6\").click(function(){\r\n");
      out.write("				var input = $(\"#input6\").val();\r\n");
      out.write("				\r\n");
      out.write("				$.ajax({\r\n");
      out.write("					url :\"jqTest6.do\",\r\n");
      out.write("					data : {\r\n");
      out.write("						keyword:input\r\n");
      out.write("					},\r\n");
      out.write("					type:\"get\",\r\n");
      out.write("					success:function(map){\r\n");
      out.write("						console.log(map);\r\n");
      out.write("						console.log(map[\"jArr\"]);\r\n");
      out.write("						\r\n");
      out.write("						var $tableBody = $(\"#memberTable6 tbody\");\r\n");
      out.write("						$tableBody.html(\"\");\r\n");
      out.write("						$.each(map[\"jArr\"], function(index, value) {\r\n");
      out.write("							console.log(value);\r\n");
      out.write("							\r\n");
      out.write("							var $tr = $(\"<tr>\");\r\n");
      out.write("							var $noTd = $(\"<td>\").text(value.no);	//<td>1</td>\r\n");
      out.write("							var $nameTd = $(\"<td>\").text(value.name);\r\n");
      out.write("							var $ageTd = $(\"<td>\").text(value.age);\r\n");
      out.write("							var $genTd = $(\"<td>\").text(value.gender);\r\n");
      out.write("							\r\n");
      out.write("							$tr.append($noTd);\r\n");
      out.write("							$tr.append($nameTd);\r\n");
      out.write("							$tr.append($ageTd);\r\n");
      out.write("							$tr.append($genTd);\r\n");
      out.write("							\r\n");
      out.write("							$tableBody.append($tr);\r\n");
      out.write("						})\r\n");
      out.write("						\r\n");
      out.write("					},\r\n");
      out.write("					error:function(e){\r\n");
      out.write("						$(\"#textArea7\").val(\"ajax 통신 실패\")\r\n");
      out.write("\r\n");
      out.write("						\r\n");
      out.write("					}\r\n");
      out.write("				})\r\n");
      out.write("				\r\n");
      out.write("			})\r\n");
      out.write("		})\r\n");
      out.write("	</script>\r\n");
      out.write("	\r\n");
      out.write("	<h3>7. Gson을 이용한 List 반환</h3>\r\n");
      out.write("	<button id=\"gbtn\">list 가져오기</button>\r\n");
      out.write("	<textarea id=\"textArea7\" rows=\"4\" cols=\"30\"></textarea>\r\n");
      out.write("	<script>\r\n");
      out.write("		$(function(){\r\n");
      out.write("			$(\"#gbtn\").click(function(){\r\n");
      out.write("				$.ajax({\r\n");
      out.write("					url :\"jqTest7.do\",\r\n");
      out.write("					type:\"get\",\r\n");
      out.write("					success:function(list){\r\n");
      out.write("						console.log(list);\r\n");
      out.write("						var result=\"\";\r\n");
      out.write("						$.each(list, function(i){\r\n");
      out.write("							result +=list[i].no+\" / \"\r\n");
      out.write("									+ list[i].name + \" / \"\r\n");
      out.write("									+ list[i].age + \" / \"\r\n");
      out.write("									+ list[i].gender + \" \\n \"\r\n");
      out.write("						})\r\n");
      out.write("						$(\"#textArea7\").val(result)\r\n");
      out.write("						\r\n");
      out.write("					},\r\n");
      out.write("					error:function(e){\r\n");
      out.write("						console.log(\"ajax 통신 실패\");\r\n");
      out.write("						\r\n");
      out.write("					}\r\n");
      out.write("				})\r\n");
      out.write("			})\r\n");
      out.write("		})\r\n");
      out.write("	</script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
