/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.69
 * Generated at: 2021-09-08 12:57:53 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.views.board;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.ArrayList;
import semiProject.com.kh.board.model.vo.*;
import semiProject.com.kh.notice.model.vo.*;
import semiProject.com.kh.member.model.vo.Member;

public final class blogListView_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/views/board/../common/footer.jsp", Long.valueOf(1631104968958L));
    _jspx_dependants.put("/views/board/../common/menubar.jsp", Long.valueOf(1631104969227L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("semiProject.com.kh.board.model.vo");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_packages.add("semiProject.com.kh.notice.model.vo");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("semiProject.com.kh.member.model.vo.Member");
    _jspx_imports_classes.add("java.util.ArrayList");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("    \r\n");

      
    ArrayList<Notice> nlist = (ArrayList<Notice>)request.getAttribute("nlist"); 
	ArrayList<Board> list  = (ArrayList<Board>)request.getAttribute("list");
	PageInfo pi = (PageInfo)request.getAttribute("pi");
	
	int listCount = pi.getListCount();
	int currentPage = pi.getCurrentPage();
	int maxPage = pi.getMaxPage();
	int startPage = pi.getStartPage();
	int endPage = pi.getEndPage();
	
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("    <meta charset=\"UTF-8\">\r\n");
      out.write("    <meta name=\"description\" content=\"Directing Template\">\r\n");
      out.write("    <meta name=\"keywords\" content=\"Directing, unica, creative, html\">\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("    <meta http-equiv=\"X-UA-Compatible\" content=\"ie=edge\">\r\n");
      out.write("    <title>어디어디 커뮤니티</title>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write(" \r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("    \r\n");
      out.write("    <!-- Page Preloder -->\r\n");
      out.write("    <div id=\"preloder\">\r\n");
      out.write("        <div class=\"loader\"></div>\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("   \r\n");
      out.write(" ");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    ");


   Member loginUser = (Member)session.getAttribute("loginUser");
	String msg = (String)session.getAttribute("msg");
   String contextPath = request.getContextPath();
   

      out.write("\r\n");
      out.write("    \r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title></title>\r\n");
      out.write("<script src=\"https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("        <!-- Css Styles -->\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"");
      out.print(contextPath );
      out.write("/resources/css/bootstrap.min.css\" type=\"text/css\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"");
      out.print(contextPath );
      out.write("/resources/css/font-awesome.min.css\" type=\"text/css\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"");
      out.print(contextPath );
      out.write("/resources/css/elegant-icons.css\" type=\"text/css\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"");
      out.print(contextPath );
      out.write("/resources/css/flaticon.css\" type=\"text/css\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"");
      out.print(contextPath );
      out.write("/resources/css/nice-select.css\" type=\"text/css\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"");
      out.print(contextPath );
      out.write("/resources/css/barfiller.css\" type=\"text/css\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"");
      out.print(contextPath );
      out.write("/resources/css/magnific-popup.css\" type=\"text/css\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"");
      out.print(contextPath );
      out.write("/resources/css/jquery-ui.min.css\" type=\"text/css\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"");
      out.print(contextPath );
      out.write("/resources/css/owl.carousel.min.css\" type=\"text/css\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"");
      out.print(contextPath );
      out.write("/resources/css/slicknav.min.css\" type=\"text/css\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"");
      out.print(contextPath );
      out.write("/resources/css/style.css\" type=\"text/css\">\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("<!-- Header Section Begin -->\r\n");
      out.write("    <header class=\"header\">\r\n");
      out.write("        <div class=\"container-fluid\">\r\n");
      out.write("            <div class=\"row\">\r\n");
      out.write("                <div class=\"col-lg-3 col-md-3\">\r\n");
      out.write("                    <div class=\"header__logo\">\r\n");
      out.write("                        <a href=\"");
      out.print(request.getContextPath());
      out.write("/index.jsp\"><img src=\"");
      out.print(request.getContextPath());
      out.write("/resources/img/Logo.png\" alt=\"야호\"></a>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"col-lg-9 col-md-9\">\r\n");
      out.write("                    <div class=\"header__nav\">\r\n");
      out.write("                        <nav class=\"header__menu mobile-menu\">\r\n");
      out.write("                            <ul>\r\n");
      out.write("                             \r\n");
      out.write("                                \r\n");
      out.write("                                <li><a href=\"");
      out.print(contextPath );
      out.write("/views/plan/planSelect.jsp\">일정플래너</a>\r\n");
      out.write("                                    \r\n");
      out.write("                                    <ul class=\"dropdown\">\r\n");
      out.write("                                        <li><a href=\"#\" onclick=\"goPlan();\">마음대로일정</a></li>\r\n");
      out.write("                                        <li><a href=\"");
      out.print(contextPath );
      out.write("/views/plan/adminRecommend.jsp\">추천일정</a></li>\r\n");
      out.write("                                        <li><a href=\"");
      out.print(contextPath );
      out.write("/list.ps\">일정보관함</a></li>\r\n");
      out.write("                                        \r\n");
      out.write("                                    </ul>\r\n");
      out.write("                                </li>\r\n");
      out.write("                                <li><a href=\"");
      out.print(contextPath );
      out.write("/views/board/faq.jsp\">FAQ</a></li>\r\n");
      out.write("                                <li><a href=\"");
      out.print(request.getContextPath() );
      out.write("/list.bo\">커뮤니티</a></li>\r\n");
      out.write("                                \r\n");
      out.write("                                ");
if(loginUser == null){
      out.write("  \r\n");
      out.write("                                <li><a href=\"");
      out.print(contextPath );
      out.write("/views/member/login.jsp\" onclick=\"goLogin();\">로그인</a></li>\r\n");
      out.write("                                <li><a href=\"");
      out.print(contextPath );
      out.write("/views/member/signUp.jsp\" onclick=\"enrollPage();\">회원가입</a></li>\r\n");
      out.write("                                 ");
}else if(loginUser.getUserId().equals("admin")) { 
      out.write("\r\n");
      out.write("                                <li><a href=\"");
      out.print(contextPath );
      out.write("/adminPage.ad\">관리자페이지</a></li>\r\n");
      out.write("                               	<li><a href=\"");
      out.print(contextPath );
      out.write("/logout.me\">로그아웃</a></li>                                \r\n");
      out.write("                                 ");
}
                                else { 
      out.write("\r\n");
      out.write("	                                <li><a href = \"");
      out.print(request.getContextPath() );
      out.write("/mypage.me\">마이페이지</a></li>\r\n");
      out.write("	                                <li><a href = \"");
      out.print(request.getContextPath() );
      out.write("/logout.me\">로그아웃</a></li>\r\n");
      out.write("							      ");
}
      out.write("\r\n");
      out.write("                            </ul>\r\n");
      out.write("                        </nav>\r\n");
      out.write("                        <div class=\"header__menu__right\">\r\n");
      out.write("                           \r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div id=\"mobile-menu-wrap\"></div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </header>\r\n");
      out.write("    <!-- Header Section End -->\r\n");
      out.write("    \r\n");
      out.write("       <script type=\"text/javascript\">\r\n");
      out.write("		   function enrollPage(){\r\n");
      out.write("			   location.href = \"");
      out.print( request.getContextPath());
      out.write("/enrollForm.me\";\r\n");
      out.write("		   }\r\n");
      out.write("   		</script>\r\n");
      out.write("    \r\n");
      out.write("    \r\n");
      out.write("      <!-- Js Plugins -->\r\n");
      out.write("    <script src=\"");
      out.print(contextPath );
      out.write("/resources/js/jquery-3.3.1.min.js\"></script>\r\n");
      out.write("    <script src=\"");
      out.print(contextPath );
      out.write("/resources/js/bootstrap.min.js\"></script>\r\n");
      out.write("    <script src=\"");
      out.print(contextPath );
      out.write("/resources/js/jquery.nice-select.min.js\"></script>\r\n");
      out.write("    <script src=\"");
      out.print(contextPath );
      out.write("/resources/js/jquery-ui.min.js\"></script>\r\n");
      out.write("    <script src=\"");
      out.print(contextPath );
      out.write("/resources/js/jquery.nicescroll.min.js\"></script>\r\n");
      out.write("    <script src=\"");
      out.print(contextPath );
      out.write("/resources/js/jquery.barfiller.js\"></script>\r\n");
      out.write("    <script src=\"");
      out.print(contextPath );
      out.write("/resources/js/jquery.magnific-popup.min.js\"></script>\r\n");
      out.write("    <script src=\"");
      out.print(contextPath );
      out.write("/resources/js/jquery.slicknav.js\"></script>\r\n");
      out.write("    <script src=\"");
      out.print(contextPath );
      out.write("/resources/js/owl.carousel.min.js\"></script>\r\n");
      out.write("    <script src=\"");
      out.print(contextPath );
      out.write("/resources/js/main.js\"></script>\r\n");
      out.write("\r\n");
      out.write("    <script src=\"");
      out.print(contextPath );
      out.write("/resources/js/modernizr.min.js\"></script>\r\n");
      out.write("    <script src=\"");
      out.print(contextPath );
      out.write("/resources/js/classie.js\"></script>\r\n");
      out.write("    <script src=\"");
      out.print(contextPath );
      out.write("/resources/js/photostack.js\"></script>\r\n");
      out.write("    \r\n");
      out.write("    <script>\r\n");
      out.write("	$(function(){\r\n");
      out.write("		var msg = \"");
      out.print(msg);
      out.write("\";\r\n");
      out.write("		if(msg != \"null\"){\r\n");
      out.write("			alert(msg);\r\n");
      out.write("			");
session.removeAttribute("msg");
      out.write("\r\n");
      out.write("		}\r\n");
      out.write("	})\r\n");
      out.write("    \r\n");
      out.write("      function goPlan(){\r\n");
      out.write("         ");
if(loginUser == null) {
      out.write("\r\n");
      out.write("            alert(\"로그인 후 이용해주세요\");\r\n");
      out.write("            location.href=\"");
      out.print(request.getContextPath());
      out.write("\";\r\n");
      out.write("         ");
}else{ 
      out.write("\r\n");
      out.write("            location.href=\"");
      out.print(request.getContextPath());
      out.write("/list.pm\";\r\n");
      out.write("         ");
} 
      out.write("\r\n");
      out.write("      } \r\n");
      out.write("   </script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
      out.write(" \r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    \r\n");
      out.write("\r\n");
      out.write("    <script>\r\n");
      out.write("        $(function () {\r\n");
      out.write("            var $header = $('header'); //헤더를 변수에 넣기\r\n");
      out.write("            var $page = $('.page-start'); //색상이 변할 부분\r\n");
      out.write("            var $window = $(window);\r\n");
      out.write("            var pageOffsetTop = $page.offset().top;//색상 변할 부분의 top값 구하기\r\n");
      out.write("\r\n");
      out.write("            $window.resize(function () { //반응형을 대비하여 리사이즈시 top값을 다시 계산\r\n");
      out.write("                pageOffsetTop = $page.offset().top;\r\n");
      out.write("            });\r\n");
      out.write("\r\n");
      out.write("            $window.on('scroll', function () { //스크롤시\r\n");
      out.write("                var scrolled = $window.scrollTop() >= pageOffsetTop; //스크롤된 상태; true or false\r\n");
      out.write("                $header.toggleClass('down', scrolled); //클래스 토글\r\n");
      out.write("            });\r\n");
      out.write("        });\r\n");
      out.write("\r\n");
      out.write("    </script>\r\n");
      out.write("\r\n");
      out.write("    <!-- Breadcrumb Begin -->\r\n");
      out.write("    <div class=\"breadcrumb-area set-bg\" data-setbg=\"");
      out.print( request.getContextPath() );
      out.write("/resources/img/breadcrumb/breadcrumb-blog.jpg\">\r\n");
      out.write("        <div class=\"container\">\r\n");
      out.write("            <div class=\"row\">\r\n");
      out.write("                <div class=\"col-lg-12 text-center\">\r\n");
      out.write("                    <div class=\"breadcrumb__text\">\r\n");
      out.write("                        <h2>커뮤니티</h2>\r\n");
      out.write("                        <div class=\"breadcrumb__option\">\r\n");
      out.write("                            <a href=\"#\"><i class=\"fa fa-home\"></i> 홈</a>\r\n");
      out.write("                            <span>커뮤니티</span>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("    <!-- Breadcrumb End -->\r\n");
      out.write("\r\n");
      out.write("    <!--폴라로이드 -->\r\n");
      out.write("\r\n");
      out.write("<section class=\"page-start\">\r\n");
      out.write("    <section id=\"photostack-1\" class=\"photostack photostack-start\">\r\n");
      out.write("        <div>\r\n");
      out.write("            <figure>\r\n");
      out.write("                <a href=\"#\" class=\"photostack-img\"><img src=\"");
      out.print( request.getContextPath() );
      out.write("/resources/img/blog/1.jpg\" alt=\"img01\" /></a>\r\n");
      out.write("                <figcaption>\r\n");
      out.write("                    <h2 class=\"photostack-title\">2020.10.17</h2>\r\n");
      out.write("                </figcaption>\r\n");
      out.write("            </figure>\r\n");
      out.write("            <figure>\r\n");
      out.write("                <a href=\"#\" class=\"photostack-img\"><img src=\"");
      out.print( request.getContextPath() );
      out.write("/resources/img/blog/2.jpg\" alt=\"img02\" /></a>\r\n");
      out.write("                <figcaption>\r\n");
      out.write("                    <h2 class=\"photostack-title\">2018.03.12</h2>\r\n");
      out.write("                </figcaption>\r\n");
      out.write("            </figure>\r\n");
      out.write("            <figure>\r\n");
      out.write("                <a href=\"#\" class=\"photostack-img\"><img src=\"");
      out.print( request.getContextPath() );
      out.write("/resources/img/blog/3.jpg\" alt=\"img03\" /></a>\r\n");
      out.write("                <figcaption>\r\n");
      out.write("                    <h2 class=\"photostack-title\">2021.06.30</h2>\r\n");
      out.write("                </figcaption>\r\n");
      out.write("            </figure>\r\n");
      out.write("            <figure>\r\n");
      out.write("                <a href=\"#\" class=\"photostack-img\"><img src=\"");
      out.print( request.getContextPath() );
      out.write("/resources/img/blog/4.jpg\" alt=\"img04\" /></a>\r\n");
      out.write("                <figcaption>\r\n");
      out.write("                    <h2 class=\"photostack-title\">2017.12.18</h2>\r\n");
      out.write("                </figcaption>\r\n");
      out.write("            </figure>\r\n");
      out.write("            <figure>\r\n");
      out.write("                <a href=\"#\" class=\"photostack-img\"><img src=\"");
      out.print( request.getContextPath() );
      out.write("/resources/img/blog/5.jpg\" alt=\"img05\" /></a>\r\n");
      out.write("                <figcaption>\r\n");
      out.write("                    <h2 class=\"photostack-title\">2020.08.25</h2>\r\n");
      out.write("                </figcaption>\r\n");
      out.write("            </figure>\r\n");
      out.write("            <figure>\r\n");
      out.write("                <a href=\"#\" class=\"photostack-img\"><img src=\"");
      out.print( request.getContextPath() );
      out.write("/resources/img/blog/6.jpg\" alt=\"img06\" /></a>\r\n");
      out.write("                <figcaption>\r\n");
      out.write("                    <h2 class=\"photostack-title\">2021.01.17</h2>\r\n");
      out.write("                </figcaption>\r\n");
      out.write("            </figure>\r\n");
      out.write("            <figure data-dummy>\r\n");
      out.write("                <a href=\"#\" class=\"photostack-img\"><img src=\"");
      out.print( request.getContextPath() );
      out.write("/resources/img/blog/7.jpg\" alt=\"img07\" /></a>\r\n");
      out.write("                <figcaption>\r\n");
      out.write("                    <h2 class=\"photostack-title\">2019.05.23</h2>\r\n");
      out.write("                </figcaption>\r\n");
      out.write("            </figure>\r\n");
      out.write("            <figure data-dummy>\r\n");
      out.write("                <a href=\"#\" class=\"photostack-img\"><img src=\"");
      out.print( request.getContextPath() );
      out.write("/resources/img/blog/8.jpg\" alt=\"img08\" /></a>\r\n");
      out.write("                <figcaption>\r\n");
      out.write("                    <h2 class=\"photostack-title\">2020.09.05</h2>\r\n");
      out.write("                </figcaption>\r\n");
      out.write("            </figure>\r\n");
      out.write("            <figure data-dummy>\r\n");
      out.write("                <a href=\"#\" class=\"photostack-img\"><img src=\"");
      out.print( request.getContextPath() );
      out.write("/resources/img/blog/9.jpg\" alt=\"img09\" /></a>\r\n");
      out.write("                <figcaption>\r\n");
      out.write("                    <h2 class=\"photostack-title\">2016.05.21</h2>\r\n");
      out.write("                </figcaption>\r\n");
      out.write("            </figure>\r\n");
      out.write("            <figure data-dummy>\r\n");
      out.write("                <a href=\"#\" class=\"photostack-img\"><img src=\"");
      out.print( request.getContextPath() );
      out.write("/resources/img/blog/10.jpg\" alt=\"img10\" /></a>\r\n");
      out.write("                <figcaption>\r\n");
      out.write("                    <h2 class=\"photostack-title\">2018.04.02</h2>\r\n");
      out.write("                </figcaption>\r\n");
      out.write("            </figure>\r\n");
      out.write("            <figure data-dummy>\r\n");
      out.write("                <a href=\"#\" class=\"photostack-img\"><img src=\"");
      out.print( request.getContextPath() );
      out.write("/resources/img/blog/11.jpg\" alt=\"img11\" /></a>\r\n");
      out.write("                <figcaption>\r\n");
      out.write("                    <h2 class=\"photostack-title\">2020.03.08</h2>\r\n");
      out.write("                </figcaption>\r\n");
      out.write("            </figure>\r\n");
      out.write("            <figure data-dummy>\r\n");
      out.write("                <a href=\"#\" class=\"photostack-img\"><img src=\"");
      out.print( request.getContextPath() );
      out.write("/resources/img/blog/12.jpg\" alt=\"img12\" /></a>\r\n");
      out.write("                <figcaption>\r\n");
      out.write("                    <h2 class=\"photostack-title\">2019.07.15</h2>\r\n");
      out.write("                </figcaption>\r\n");
      out.write("            </figure>\r\n");
      out.write("            <figure data-dummy>\r\n");
      out.write("                <a href=\"#\" class=\"photostack-img\"><img src=\"");
      out.print( request.getContextPath() );
      out.write("/resources/img/blog/13.jpg\" alt=\"img13\" /></a>\r\n");
      out.write("                <figcaption>\r\n");
      out.write("                    <h2 class=\"photostack-title\">2021.05.30</h2>\r\n");
      out.write("                </figcaption>\r\n");
      out.write("            </figure>\r\n");
      out.write("            <figure data-dummy>\r\n");
      out.write("                <a href=\"#\" class=\"photostack-img\"><img src=\"");
      out.print( request.getContextPath() );
      out.write("/resources/img/blog/14.jpg\" alt=\"img14\" /></a>\r\n");
      out.write("                <figcaption>\r\n");
      out.write("                    <h2 class=\"photostack-title\">2017.06.04</h2>\r\n");
      out.write("                </figcaption>\r\n");
      out.write("            </figure>\r\n");
      out.write("            <figure data-dummy>\r\n");
      out.write("                <a href=\"#\" class=\"photostack-img\"><img src=\"");
      out.print( request.getContextPath() );
      out.write("/resources/img/blog/15.jpg\" alt=\"img15\" /></a>\r\n");
      out.write("                <figcaption>\r\n");
      out.write("                    <h2 class=\"photostack-title\">2020.08.23</h2>\r\n");
      out.write("                </figcaption>\r\n");
      out.write("            </figure>\r\n");
      out.write("            <figure data-dummy>\r\n");
      out.write("                <a href=\"#\" class=\"photostack-img\"><img src=\"");
      out.print( request.getContextPath() );
      out.write("/resources/img/blog/16.jpg\" alt=\"img16\" /></a>\r\n");
      out.write("                <figcaption>\r\n");
      out.write("                    <h2 class=\"photostack-title\">2019.10.20</h2>\r\n");
      out.write("                </figcaption>\r\n");
      out.write("            </figure>\r\n");
      out.write("        </div>\r\n");
      out.write("    </section>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    <!-- 폴라로이드  end-->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!-- =================QnA =============== -->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<section class=\"faq bg-color\">\r\n");
      out.write("      <div class=\"container\">\r\n");
      out.write("        <div class=\"faq-title\">\r\n");
      out.write("          <h2>공지사항</h2>\r\n");
      out.write("          <p>어디어디 공지사항입니다!</p>\r\n");
      out.write("        </div>\r\n");
      out.write("        \r\n");
      out.write("        ");
 if(nlist.isEmpty()){ 
      out.write("\r\n");
      out.write("        ");
 System.out.print(nlist); 
      out.write("\r\n");
      out.write("        <div><p>공지사항이 없습니다.</p></div>\r\n");
      out.write("        \r\n");
      out.write("        \r\n");
      out.write("        ");
 }else{  
      out.write("\r\n");
      out.write("				 ");
 for(Notice n : nlist){ 
      out.write("\r\n");
      out.write("		<ul class=\"faq-list\">\r\n");
      out.write("          <li data-aos=\"fade-up\" data-aos-delay=\"100\" class=\"aos-init aos-animate\">\r\n");
      out.write("            <a data-toggle=\"collapse\" class=\"collapsed\" href=\"#faq1\" aria-expanded=\"false\">");
      out.print( n.getNoticeTitle() );
      out.write(" <i class=\"fas fa-arrow-up\"></i></a>\r\n");
      out.write("            <div id=\"faq1\" class=\"collapse\" data-parent=\".faq-list\" style=\"\">\r\n");
      out.write("              <p>\r\n");
      out.write("                ");
      out.print( n.getNoticeContent() );
      out.write("\r\n");
      out.write("              </p>\r\n");
      out.write("            </div>\r\n");
      out.write("          </li>\r\n");
      out.write("          </ul>\r\n");
      out.write("				");
 } 
      out.write("\r\n");
      out.write("			");
 } 
      out.write("\r\n");
      out.write("          \r\n");
      out.write("        \r\n");
      out.write("      </div>\r\n");
      out.write("      \r\n");
      out.write("     \r\n");
      out.write("    </section>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!-- =================QnA end =============== -->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    <!-- Blog Section Begin -->\r\n");
      out.write("    <section class=\"blog-section spad\">\r\n");
      out.write("        <div class=\"container\">\r\n");
      out.write("            <div class=\"row\">\r\n");
      out.write("                <div class=\"col-lg-8\">\r\n");
      out.write("                    <div class=\"blog__item__large\">\r\n");
      out.write("                    \r\n");
      out.write("                        <a href=\"");
      out.print( request.getContextPath() );
      out.write("/views/board/blogDetails.jsp\">\r\n");
      out.write("                        \r\n");
      out.write("                        <div class=\"blog__item__pic set-bg\" data-setbg=\"");
      out.print( request.getContextPath() );
      out.write("/resources/img/blog/seoul.jpg\"></div>\r\n");
      out.write("                        </a>\r\n");
      out.write("                        <div class=\"blog__item__text\">\r\n");
      out.write("                           \r\n");
      out.write("                            <h3><a href=\"#\">Internet Banner Advertising Most Reliable</a></h3>\r\n");
      out.write("                            <ul class=\"blog__item__widget\">\r\n");
      out.write("                                <li><i class=\"fa fa-clock-o\"></i> 19th March, 2019</li>\r\n");
      out.write("                                <li><i class=\"fa fa-user\"></i> John Smith</li>\r\n");
      out.write("                            </ul>\r\n");
      out.write("                            <p>One of my favorite things I like to watch is the bloopers and outtakes that are shown of\r\n");
      out.write("                                mistakes made during the making of a movie.</p>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    \r\n");
      out.write("                    \r\n");
      out.write("                    <div class=\"row\">\r\n");
      out.write("                    \r\n");
      out.write("                    \r\n");
      out.write("                    ");
if(list.isEmpty()){ 
      out.write("\r\n");
      out.write("				\r\n");
      out.write("					<p>조회된 리스트가 없습니다.</p>\r\n");
      out.write("				\r\n");
      out.write("					");
}else{ 
      out.write("\r\n");
      out.write("					");
 for(Board b : list){ 
      out.write("\r\n");
      out.write("                    \r\n");
      out.write("                    \r\n");
      out.write("                        <div class=\"col-lg-6 col-md-6\">\r\n");
      out.write("                            <div class=\"blog__item\">\r\n");
      out.write("                                <a href=\"");
      out.print(request.getContextPath() );
      out.write("/detail.bo\">\r\n");
      out.write("                                \r\n");
      out.write("                                <input type=\"hidden\" value=\"");
      out.print(b.getBoardNo());
      out.write("\">\r\n");
      out.write("                                <div class=\"blog__item__pic set-bg\" data-setbg=\"");
      out.print(contextPath );
      out.write("/resources/board_upfiles/");
      out.print( b.getTitleImg() );
      out.write("\" >\r\n");
      out.write("				               ");
      out.write("\r\n");
      out.write("				               \r\n");
      out.write("				               \r\n");
      out.write("                                </div>\r\n");
      out.write("                                </a>\r\n");
      out.write("                                <div class=\"blog__item__text\">\r\n");
      out.write("                                   \r\n");
      out.write("                                    <h5><a href=\"");
      out.print(request.getContextPath() );
      out.write("/detail.bo\">");
      out.print( b.getBoardTitle() );
      out.write("</a></h5>\r\n");
      out.write("                                    <ul class=\"blog__item__widget\">\r\n");
      out.write("                                        <li><i class=\"fa fa-clock-o\"></i> ");
      out.print( b.getCreateDate() );
      out.write("</li>\r\n");
      out.write("                                        <li><i class=\"fa fa-user\"></i> ");
      out.print( b.getBoardWriter() );
      out.write("</li>\r\n");
      out.write("                                        <li><i class=\"fa fa-heart\"></i> ");
      out.print( b.getCount() );
      out.write("</li>\r\n");
      out.write("                                       \r\n");
      out.write("                                    </ul>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        \r\n");
      out.write("                        ");
} 
      out.write("\r\n");
      out.write("				");
} 
      out.write("\r\n");
      out.write("                      \r\n");
      out.write("                        \r\n");
      out.write("                        \r\n");
      out.write("                    </div>\r\n");
      out.write("                    \r\n");
      out.write("                    \r\n");
      out.write("\r\n");
      out.write("<!----------------------- 페이징바 만들기 -------------------------------->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("		<div class=\"blog__pagination\" >\r\n");
      out.write("			<!-- 맨 처음으로 (<<) -->\r\n");
      out.write("			<a href=\"");
      out.print(contextPath);
      out.write("/list.bo?currentPage=1\"> &lt;&lt; </a>\r\n");
      out.write("			\r\n");
      out.write("		\r\n");
      out.write("			<!-- 이전페이지로(<) -->\r\n");
      out.write("			");
if(currentPage == 1){ 
      out.write("\r\n");
      out.write("			<a class=\"noHover\"> &lt; </a>\r\n");
      out.write("			");
}else{ 
      out.write("\r\n");
      out.write("			<a href=\"");
      out.print( contextPath );
      out.write("/list.bo?currentPage=");
      out.print( currentPage-1 );
      out.write("\"> &lt; </a>\r\n");
      out.write("			");
} 
      out.write("\r\n");
      out.write("			\r\n");
      out.write("			<!-- 페이지 목록 -->\r\n");
      out.write("			");
for(int p=startPage; p<=endPage; p++){ 
      out.write("\r\n");
      out.write("				\r\n");
      out.write("				");
if(p == currentPage){ 
      out.write("\r\n");
      out.write("				<a class=\"noHover\"> ");
      out.print( p );
      out.write(" </a>\r\n");
      out.write("				");
}else{ 
      out.write("\r\n");
      out.write("				<a href=\"");
      out.print(contextPath );
      out.write("/list.bo?currentPage=");
      out.print( p );
      out.write('"');
      out.write('>');
      out.write(' ');
      out.print( p );
      out.write(" </a>\r\n");
      out.write("				");
} 
      out.write("\r\n");
      out.write("				\r\n");
      out.write("			");
} 
      out.write("\r\n");
      out.write("			\r\n");
      out.write("			<!-- 다음페이지로(>) -->\r\n");
      out.write("			");
if(currentPage == maxPage){ 
      out.write("\r\n");
      out.write("			<a class=\"noHover\"> &gt; </a>\r\n");
      out.write("			");
}else { 
      out.write("\r\n");
      out.write("			<a href=\"");
      out.print( contextPath );
      out.write("/list.bo?currentPage=");
      out.print( currentPage+1 );
      out.write("\"> &gt; </a>\r\n");
      out.write("			");
} 
      out.write("\r\n");
      out.write("		\r\n");
      out.write("			<!-- 맨 끝으로 (>>) -->\r\n");
      out.write("			<a href=\"");
      out.print(contextPath);
      out.write("/list.bo?currentPage=");
      out.print(maxPage);
      out.write("\"> &gt;&gt; </a>\r\n");
      out.write("		</div> \r\n");
      out.write("                    \r\n");
      out.write("          <br><br><br>          \r\n");
      out.write("           ");
 if(loginUser != null){ 
      out.write("\r\n");
      out.write("			<button  type=\"submit\" class=\"site-btn\" onclick=\"location.href='enroll.bo'\">글쓰기</button>\r\n");
      out.write("		");
 }else {
      out.write("         \r\n");
      out.write("                    \r\n");
      out.write("			<button type=\"submit\" class=\"site-btn\" onclick=\"pop();\">글쓰기</button>\r\n");
      out.write("                    \r\n");
      out.write("            ");
 } 
      out.write("        \r\n");
      out.write("                    \r\n");
      out.write("           \r\n");
      out.write("           \r\n");
      out.write("           <script type=\"text/javascript\">\r\n");
      out.write("				function pop(){\r\n");
      out.write("					alert(\"로그인후 사용가능합니다.\")\r\n");
      out.write("				}\r\n");
      out.write("	\r\n");
      out.write("	\r\n");
      out.write("				\r\n");
      out.write("			\r\n");
      out.write("				\r\n");
      out.write("				");
if(!list.isEmpty()){
      out.write("\r\n");
      out.write("				$(function(){\r\n");
      out.write("					$(\".blog__item>a\").click(function(){\r\n");
      out.write("						var bno = $(this).children().eq(0).text();\r\n");
      out.write("						location.href=\"");
      out.print( contextPath);
      out.write("/detail.bo?bno=\"+bno;\r\n");
      out.write("						console.log(bno);\r\n");
      out.write("					})\r\n");
      out.write("				})\r\n");
      out.write("				");
}
      out.write("\r\n");
      out.write("			\r\n");
      out.write("				\r\n");
      out.write("		</script>\r\n");
      out.write("           \r\n");
      out.write("                    \r\n");
      out.write("                    \r\n");
      out.write(" \r\n");
      out.write("                    \r\n");
      out.write("                    \r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"col-lg-4\">\r\n");
      out.write("                    <div class=\"blog__sidebar\">\r\n");
      out.write("                        <div class=\"blog__sidebar__search\">\r\n");
      out.write("                            <form action=\"#\">\r\n");
      out.write("                                <input type=\"text\" placeholder=\"Searching...\">\r\n");
      out.write("                                <button type=\"submit\"><i class=\"fa fa-search\"></i></button>\r\n");
      out.write("                            </form>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"blog__sidebar__recent\">\r\n");
      out.write("                            <h5>Recent Post</h5>\r\n");
      out.write("                            <a href=\"#\" class=\"blog__sidebar__recent__item\">\r\n");
      out.write("                                <div class=\"blog__sidebar__recent__item__pic\">\r\n");
      out.write("                                    <img src=\"");
      out.print( request.getContextPath() );
      out.write("/resources/img/blog/recent-1.jpg\" alt=\"\">\r\n");
      out.write("                                </div>\r\n");
      out.write("                                <div class=\"blog__sidebar__recent__item__text\">\r\n");
      out.write("                                <span class=\"lanking\">1</span>\r\n");
      out.write("                                    <h6>Tortoise grilled on salt</h6>\r\n");
      out.write("                                    <p><i class=\"fa fa-clock-o\"></i> 19th March, 2019</p>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </a>\r\n");
      out.write("                            <a href=\"#\" class=\"blog__sidebar__recent__item\">\r\n");
      out.write("                                <div class=\"blog__sidebar__recent__item__pic\">\r\n");
      out.write("                                    <img src=\"");
      out.print( request.getContextPath() );
      out.write("/resources/img/blog/recent-2.jpg\" alt=\"\">\r\n");
      out.write("                                </div>\r\n");
      out.write("                                <div class=\"blog__sidebar__recent__item__text\">\r\n");
      out.write("                                    <span class=\"lanking\">2</span>\r\n");
      out.write("                                    <h6>Shrimp floured and fried</h6>\r\n");
      out.write("                                    <p><i class=\"fa fa-clock-o\"></i> 22th March, 2019</p>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </a>\r\n");
      out.write("                            <a href=\"#\" class=\"blog__sidebar__recent__item\">\r\n");
      out.write("                                <div class=\"blog__sidebar__recent__item__pic\">\r\n");
      out.write("                                    <img src=\"");
      out.print( request.getContextPath() );
      out.write("/resources/img/blog/recent-3.jpg\" alt=\"\">\r\n");
      out.write("                                </div>\r\n");
      out.write("                                <div class=\"blog__sidebar__recent__item__text\">\r\n");
      out.write("                                    <span class=\"lanking\">3</span>\r\n");
      out.write("                                    <h6>Sweet and sour pork ribs</h6>\r\n");
      out.write("                                    <p><i class=\"fa fa-clock-o\"></i> 25th March, 2019</p>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </a>\r\n");
      out.write("                            <a href=\"#\" class=\"blog__sidebar__recent__item\">\r\n");
      out.write("                                <div class=\"blog__sidebar__recent__item__pic\">\r\n");
      out.write("                                    <img src=\"");
      out.print( request.getContextPath() );
      out.write("/resources/img/blog/recent-4.jpg\" alt=\"\">\r\n");
      out.write("                                </div>\r\n");
      out.write("                                <div class=\"blog__sidebar__recent__item__text\">\r\n");
      out.write("                                    <span class=\"lanking\">4</span>\r\n");
      out.write("                                    <h6>Crab fried with tamarind</h6>\r\n");
      out.write("                                    <p><i class=\"fa fa-clock-o\"></i> 19th March, 2019</p>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </a>\r\n");
      out.write("                            <a href=\"#\" class=\"blog__sidebar__recent__item\">\r\n");
      out.write("                                <div class=\"blog__sidebar__recent__item__pic\">\r\n");
      out.write("                                    <img src=\"");
      out.print( request.getContextPath() );
      out.write("/resources/img/blog/recent-5.jpg\" alt=\"\">\r\n");
      out.write("                                </div>\r\n");
      out.write("                                <div class=\"blog__sidebar__recent__item__text\">\r\n");
      out.write("                                <span class=\"lanking\">5</span>\r\n");
      out.write("                                    <h6>Tortoise grilled on salt</h6>\r\n");
      out.write("                                    <p><i class=\"fa fa-clock-o\"></i> 19th March, 2019</p>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </a>\r\n");
      out.write("                        </div>\r\n");
      out.write("                       \r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </section>\r\n");
      out.write("    <!-- Blog Section End -->\r\n");
      out.write("\r\n");
      out.write("</section>\r\n");
      out.write("\r\n");
      out.write("    \r\n");
      out.write("	\r\n");
      out.write("    \r\n");
      out.write("   \r\n");
      out.write("    <!-- Js Plugins -->\r\n");
      out.write("   \r\n");
      out.write("    \r\n");
      out.write("    <script src=\"");
      out.print( contextPath );
      out.write("/resources/js/main.js\"></script>\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"https://pro.fontawesome.com/releases/v5.10.0/css/all.css\" integrity=\"sha384-AYmEC3Yw5cVb3ZcuHtOA93w35dYTsvhLPVnYs9eStHfGJvOvKxVfELGroGkvsg+p\" crossorigin=\"anonymous\"/>\r\n");
      out.write("\r\n");
      out.write("    \r\n");
      out.write("     ");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title></title>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    \r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("<!-- Footer Section Begin -->\r\n");
      out.write("    <footer class=\"footer\">\r\n");
      out.write("        <div class=\"container\">\r\n");
      out.write("            <div class=\"row\">\r\n");
      out.write("                <div class=\"col-lg-4 col-md-6\">\r\n");
      out.write("                    <div class=\"footer__about\">\r\n");
      out.write("                        <div class=\"footer__about__logo\">\r\n");
      out.write("                            <a href=\"");
      out.print(request.getContextPath());
      out.write("/index.jsp\"><img src=\"");
      out.print(request.getContextPath());
      out.write("/resources/img/Logo_D_1.png\" alt=\"\"></a>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <p>어디갈까 고민될 때는 어디어디!! &#128150;<br>\r\n");
      out.write("                        어디어디와 함께라면 지루한 일상도 특별하게\r\n");
      out.write("\r\n");
      out.write("                        </p>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"col-lg-6 offset-lg-2 col-md-6\">\r\n");
      out.write("                    <div class=\"footer__address\">\r\n");
      out.write("                        <ul>\r\n");
      out.write("                            <li>\r\n");
      out.write("                                <span>전화번호:</span>\r\n");
      out.write("                                <p>(+12) 345-678-910</p>\r\n");
      out.write("                            </li>\r\n");
      out.write("                            <li>\r\n");
      out.write("                                <span>이메일:</span>\r\n");
      out.write("                                <p>info.colorlib@gmail .com</p>\r\n");
      out.write("                            </li>\r\n");
      out.write("                            <li>\r\n");
      out.write("                                <span>주소:</span>\r\n");
      out.write("                                <p>서울특별시 강남구<br> 테헤란로14길 6</p>\r\n");
      out.write("                            </li>\r\n");
      out.write("                            <li>\r\n");
      out.write("                                <span>Connect Us:</span>\r\n");
      out.write("                                <div class=\"footer__social\">\r\n");
      out.write("                                    <a href=\"#\"><i class=\"fa fa-facebook\"></i></a>\r\n");
      out.write("                                    <a href=\"#\"><i class=\"fa fa-instagram\"></i></a>\r\n");
      out.write("                                    <a href=\"#\"><i class=\"fa fa-twitter\"></i></a>\r\n");
      out.write("                                    <a href=\"#\"><i class=\"fa fa-skype\"></i></a>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </li>\r\n");
      out.write("                        </ul>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("              \r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"row\">\r\n");
      out.write("                <div class=\"col-lg-12\">\r\n");
      out.write("                    <div class=\"footer__copyright\">\r\n");
      out.write("                        <div class=\"footer__copyright__text\"><p><!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->\r\n");
      out.write("  Copyright &copy;<script>document.write(new Date().getFullYear());</script> img by pngtree, Korea tourism oranization <i class=\"fa fa-heart\" aria-hidden=\"true\"></i> by <a href=\"https://colorlib.com\" target=\"_blank\">Colorlib</a>\r\n");
      out.write("  <!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. --></p>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"footer__copyright__links\">\r\n");
      out.write("                            <a href=\"#\">서비스 소개</a>\r\n");
      out.write("                            <a href=\"#\">이용약관</a>\r\n");
      out.write("                            <a href=\"#\">개인정보처리방침</a>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </footer>\r\n");
      out.write("    <!-- Footer Section End -->\r\n");
      out.write("\r\n");
      out.write("  \r\n");
      out.write(" \r\n");
      out.write(" \r\n");
      out.write("    \r\n");
      out.write("   \r\n");
      out.write("    \r\n");
      out.write("</body>\r\n");
      out.write("</html>");
      out.write(" \r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
