/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.69
 * Generated at: 2021-09-13 12:25:14 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.views.plan;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.*;
import semiProject.com.kh.planAdmin.model.vo.*;
import semiProject.com.kh.course.model.vo.*;
import semiProject.com.kh.member.model.vo.Member;

public final class adminRecommend_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/views/plan/../common/footer.jsp", Long.valueOf(1631306542650L));
    _jspx_dependants.put("/views/plan/../common/menubar.jsp", Long.valueOf(1631516282418L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("semiProject.com.kh.planAdmin.model.vo");
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("java.util");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("semiProject.com.kh.course.model.vo");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("semiProject.com.kh.member.model.vo.Member");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("    \r\n");
      out.write("    \r\n");
      out.write("   \r\n");
      out.write("    ");

   
 //   AdminPlan apList = (AdminPlan) request.getAttribute("apList");
   /*  ArrayList<Course>cList = ( ArrayList<Course>) request.getAttribute("cList"); */
    
    
      out.write("\r\n");
      out.write("\r\n");
      out.write("  \r\n");
      out.write("	\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("\r\n");
      out.write("<head>\r\n");
      out.write("    <meta charset=\"UTF-8\">\r\n");
      out.write("    <meta name=\"description\" content=\"Directing Template\">\r\n");
      out.write("    <meta name=\"keywords\" content=\"Directing, unica, creative, html\">\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("    <meta http-equiv=\"X-UA-Compatible\" content=\"ie=edge\">\r\n");
      out.write("    <title>어디어디</title>\r\n");
      out.write("\r\n");
      out.write("    <!-- Google Font -->\r\n");
      out.write("    <link href=\"https://fonts.googleapis.com/css2?family=Open+Sans:wght@400;600;700;800&display=swap\" rel=\"stylesheet\">\r\n");
      out.write("\r\n");
      out.write("    <!--JS-->\r\n");
      out.write("    <script src=\"https://code.jquery.com/jquery-3.3.1.slim.min.js\" integrity=\"sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo\" crossorigin=\"anonymous\"></script>\r\n");
      out.write("    <script src=\"https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js\" integrity=\"sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy\" crossorigin=\"anonymous\"></script>\r\n");
      out.write("\r\n");
      out.write("	<!-- 제이쿼리 피커데이트 -->\r\n");
      out.write("	<link rel=\"stylesheet\" href=\"//code.jquery.com/ui/1.11.4/themes/smoothness/jquery-ui.css\">\r\n");
      out.write("	<script src=\"//code.jquery.com/jquery.min.js\"></script>\r\n");
      out.write("	<script src=\"//code.jquery.com/ui/1.11.4/jquery-ui.min.js\"></script>\r\n");
      out.write("	\r\n");
      out.write("	\r\n");
      out.write("	<!--드롭다운-->\r\n");
      out.write("	<link rel=\"stylesheet\" href=\"https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css\" integrity=\"sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm\" crossorigin=\"anonymous\">\r\n");
      out.write("	<script src=\"https://code.jquery.com/jquery-3.2.1.slim.min.js\" integrity=\"sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN\" crossorigin=\"anonymous\"></script>\r\n");
      out.write("	<script src=\"https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js\" integrity=\"sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q\" crossorigin=\"anonymous\"></script>\r\n");
      out.write("	\r\n");
      out.write("	\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("		<style>\r\n");
      out.write("		\r\n");
      out.write("		/* 위치 */\r\n");
      out.write("		.loca_1{\r\n");
      out.write("			float: left;\r\n");
      out.write("			margin-left: 10%;\r\n");
      out.write("			text-align: center;\r\n");
      out.write("			border: 1px solid pink;\r\n");
      out.write("			background-color: #D958A0;\r\n");
      out.write("			padding: 5%;\r\n");
      out.write("			border-radius: 2em;\r\n");
      out.write("		}\r\n");
      out.write("		\r\n");
      out.write("		/* 날짜 */\r\n");
      out.write("		.date_1{ \r\n");
      out.write("			float: right;\r\n");
      out.write("			margin-right: 10%;\r\n");
      out.write("			text-align: center;\r\n");
      out.write("			border: 1px solid pink;\r\n");
      out.write("			background-color: #D958A0;\r\n");
      out.write("			padding: 5%;\r\n");
      out.write("			border-radius: 2em;\r\n");
      out.write("			\r\n");
      out.write("		}\r\n");
      out.write("		\r\n");
      out.write("		.title{\r\n");
      out.write("		\r\n");
      out.write("		\r\n");
      out.write("		}\r\n");
      out.write("		</style>\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("    <!-- Page Preloder -->\r\n");
      out.write("	<!-- <div id=\"preloder\">\r\n");
      out.write("        <div class=\"loader\"></div>\r\n");
      out.write("    </div> -->\r\n");
      out.write("\r\n");
      out.write("     ");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    ");


   Member loginUser = (Member)session.getAttribute("loginUser");
	String msg = (String)session.getAttribute("msg");
   String contextPath = request.getContextPath();
   

      out.write("\r\n");
      out.write("    \r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title></title>\r\n");
      out.write("<script src=\"https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("        <!-- Css Styles -->\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"");
      out.print(contextPath );
      out.write("/resources/css/bootstrap.min.css\" type=\"text/css\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"");
      out.print(contextPath );
      out.write("/resources/css/font-awesome.min.css\" type=\"text/css\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"");
      out.print(contextPath );
      out.write("/resources/css/elegant-icons.css\" type=\"text/css\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"");
      out.print(contextPath );
      out.write("/resources/css/flaticon.css\" type=\"text/css\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"");
      out.print(contextPath );
      out.write("/resources/css/nice-select.css\" type=\"text/css\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"");
      out.print(contextPath );
      out.write("/resources/css/barfiller.css\" type=\"text/css\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"");
      out.print(contextPath );
      out.write("/resources/css/magnific-popup.css\" type=\"text/css\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"");
      out.print(contextPath );
      out.write("/resources/css/jquery-ui.min.css\" type=\"text/css\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"");
      out.print(contextPath );
      out.write("/resources/css/owl.carousel.min.css\" type=\"text/css\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"");
      out.print(contextPath );
      out.write("/resources/css/slicknav.min.css\" type=\"text/css\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"");
      out.print(contextPath );
      out.write("/resources/css/style.css\" type=\"text/css\">\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("<!-- Header Section Begin -->\r\n");
      out.write("    <header class=\"header\">\r\n");
      out.write("        <div class=\"container-fluid\">\r\n");
      out.write("            <div class=\"row\">\r\n");
      out.write("                <div class=\"col-lg-3 col-md-3\">\r\n");
      out.write("                    <div class=\"header__logo\">\r\n");
      out.write("                        <a href=\"");
      out.print(request.getContextPath());
      out.write("/index.jsp\"><img src=\"");
      out.print(request.getContextPath());
      out.write("/resources/img/Logo.png\" alt=\"야호\"></a>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"col-lg-9 col-md-9\">\r\n");
      out.write("                    <div class=\"header__nav\">\r\n");
      out.write("                        <nav class=\"header__menu mobile-menu\">\r\n");
      out.write("                            <ul>\r\n");
      out.write("                             \r\n");
      out.write("                                \r\n");
      out.write("                                <li><a href=\"");
      out.print(contextPath );
      out.write("/views/plan/planSelect.jsp\">일정플래너</a>\r\n");
      out.write("                                    \r\n");
      out.write("                                    <ul class=\"dropdown\">\r\n");
      out.write("                                        <li><a href=\"#\" class=\"movePage\">마음대로일정</a></li>\r\n");
      out.write("                                        <li><a href=\"");
      out.print(contextPath );
      out.write("/views/plan/adminRecommend.jsp\">추천일정</a></li>\r\n");
      out.write("                                        <li><a href=\"#\" class=\"movePage\">일정보관함</a></li>\r\n");
      out.write("                                        \r\n");
      out.write("                                    </ul>\r\n");
      out.write("                                </li>\r\n");
      out.write("                                \r\n");
      out.write("                                <li><a href=\"");
      out.print(request.getContextPath() );
      out.write("/list.bo\">커뮤니티</a></li>\r\n");
      out.write("                                \r\n");
      out.write("                                ");
if(loginUser == null){
      out.write("  \r\n");
      out.write("                                <li><a href=\"");
      out.print(contextPath );
      out.write("/views/member/login.jsp\" onclick=\"goLogin();\">로그인</a></li>\r\n");
      out.write("                                <li><a href=\"");
      out.print(contextPath );
      out.write("/views/member/signUp.jsp\" onclick=\"enrollPage();\">회원가입</a></li>\r\n");
      out.write("                                 ");
}else if(loginUser.getUserId().equals("admin")) { 
      out.write("\r\n");
      out.write("                                <li><a href=\"");
      out.print(contextPath );
      out.write("/adminPage.ad\">관리자페이지</a></li>\r\n");
      out.write("                               	<li><a href=\"");
      out.print(contextPath );
      out.write("/logout.me\">로그아웃</a></li>                                \r\n");
      out.write("                                 ");
}
                                else { 
      out.write("\r\n");
      out.write("	                                <li><a href = \"");
      out.print(request.getContextPath() );
      out.write("/mypage.me\">마이페이지</a></li>\r\n");
      out.write("	                                <li><a href = \"");
      out.print(request.getContextPath() );
      out.write("/logout.me\">로그아웃</a></li>\r\n");
      out.write("							      ");
}
      out.write("\r\n");
      out.write("                            </ul>\r\n");
      out.write("                        </nav>\r\n");
      out.write("                        <div class=\"header__menu__right\">\r\n");
      out.write("                           \r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div id=\"mobile-menu-wrap\"></div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </header>\r\n");
      out.write("    <!-- Header Section End -->\r\n");
      out.write("    \r\n");
      out.write("       <script type=\"text/javascript\">\r\n");
      out.write("		   function enrollPage(){\r\n");
      out.write("			   location.href = \"");
      out.print( request.getContextPath());
      out.write("/enrollForm.me\";\r\n");
      out.write("		   }\r\n");
      out.write("		   \r\n");
      out.write("		   //로그인 상태에 따라 plan페이지 이동\r\n");
      out.write("		   $(function(){\r\n");
      out.write("			   $('.movePage').click(function(){\r\n");
      out.write("	               var text = $(this).text();\r\n");
      out.write("	               ");
if(loginUser == null) {
      out.write("  //로그인 X -> 로그인페이지로 이동\r\n");
      out.write("	                    alert(\"로그인 후 이용해주세요\");\r\n");
      out.write("	                    location.href=\"");
      out.print(contextPath);
      out.write("/views/member/login.jsp\";\r\n");
      out.write("	               ");
}else{ 
      out.write("\r\n");
      out.write("	                    if(text == \"마음대로일정\"){\r\n");
      out.write("	                      	 location.href=\"");
      out.print(contextPath);
      out.write("/list.pm\";	\r\n");
      out.write("	                    }else if(text == \"일정보관함\"){\r\n");
      out.write("	                        location.href=\"");
      out.print(contextPath);
      out.write("/list.ps\";\r\n");
      out.write("	                    }\r\n");
      out.write("	               ");
}
      out.write("\r\n");
      out.write("	           })\r\n");
      out.write("		   })\r\n");
      out.write("   		</script>\r\n");
      out.write("    \r\n");
      out.write("    \r\n");
      out.write("      <!-- Js Plugins -->\r\n");
      out.write("    <script src=\"");
      out.print(contextPath );
      out.write("/resources/js/jquery-3.3.1.min.js\"></script>\r\n");
      out.write("    <script src=\"");
      out.print(contextPath );
      out.write("/resources/js/bootstrap.min.js\"></script>\r\n");
      out.write("    <script src=\"");
      out.print(contextPath );
      out.write("/resources/js/jquery.nice-select.min.js\"></script>\r\n");
      out.write("    <script src=\"");
      out.print(contextPath );
      out.write("/resources/js/jquery-ui.min.js\"></script>\r\n");
      out.write("    <script src=\"");
      out.print(contextPath );
      out.write("/resources/js/jquery.nicescroll.min.js\"></script>\r\n");
      out.write("    <script src=\"");
      out.print(contextPath );
      out.write("/resources/js/jquery.barfiller.js\"></script>\r\n");
      out.write("    <script src=\"");
      out.print(contextPath );
      out.write("/resources/js/jquery.magnific-popup.min.js\"></script>\r\n");
      out.write("    <script src=\"");
      out.print(contextPath );
      out.write("/resources/js/jquery.slicknav.js\"></script>\r\n");
      out.write("    <script src=\"");
      out.print(contextPath );
      out.write("/resources/js/owl.carousel.min.js\"></script>\r\n");
      out.write("    <script src=\"");
      out.print(contextPath );
      out.write("/resources/js/main.js\"></script>\r\n");
      out.write("\r\n");
      out.write("    <script src=\"");
      out.print(contextPath );
      out.write("/resources/js/modernizr.min.js\"></script>\r\n");
      out.write("    <script src=\"");
      out.print(contextPath );
      out.write("/resources/js/classie.js\"></script>\r\n");
      out.write("    <script src=\"");
      out.print(contextPath );
      out.write("/resources/js/photostack.js\"></script>\r\n");
      out.write("    \r\n");
      out.write("    <script>\r\n");
      out.write("	$(function(){\r\n");
      out.write("		var msg = \"");
      out.print(msg);
      out.write("\";\r\n");
      out.write("		if(msg != \"null\"){\r\n");
      out.write("			alert(msg);\r\n");
      out.write("			");
session.removeAttribute("msg");
      out.write("\r\n");
      out.write("		}\r\n");
      out.write("	})\r\n");
      out.write("\r\n");
      out.write("   </script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("		<!-- 페이지 상단부  -->\r\n");
      out.write("		<!-- Listing Section Begin  -->\r\n");
      out.write("		<section class=\"listing-hero set-bg\" data-setbg=\"");
      out.print( contextPath );
      out.write("/resources/img/breadcrumb/breadcrumb-blog2.gif\">\r\n");
      out.write("		<div class=\"container\">\r\n");
      out.write("		    <div class=\"row\">\r\n");
      out.write("		        <div class=\"col-lg-8\">\r\n");
      out.write("		            <div class=\"listing__hero__option\">\r\n");
      out.write("		\r\n");
      out.write("		                <div class=\"listing__hero__text\">\r\n");
      out.write("		                    <h2>추천 일정</h2>\r\n");
      out.write("		                    <div class=\"breadcrumb__option\">\r\n");
      out.write("		                        <a href=\"./index.jsp\"><i class=\"fa fa-home\"></i> 홈</a>\r\n");
      out.write("		                        <span>추천일정</span>\r\n");
      out.write("		                    </div>\r\n");
      out.write("		                    <p> 테마와 위치 날짜를 선택하시면 일정을 추천해 드립니다!</p>\r\n");
      out.write("		                </div>\r\n");
      out.write("		            </div>\r\n");
      out.write("		        </div>\r\n");
      out.write("		\r\n");
      out.write("		    </div>\r\n");
      out.write("		</div>\r\n");
      out.write("		</section>\r\n");
      out.write("\r\n");
      out.write("<section class=\"page-start\">\r\n");
      out.write("    <!--메뉴바 같이 내려오는 시작점 -->\r\n");
      out.write("\r\n");
      out.write("    <section class=\"most-search spad\">\r\n");
      out.write("        <section class=\"most-search spad\">\r\n");
      out.write("            <div class=\"container\">\r\n");
      out.write("                <div class=\"row\">\r\n");
      out.write("                    <div class=\"col-lg-12\">\r\n");
      out.write("                        <div class=\"section-title\">\r\n");
      out.write("                            <h2>STEP 1</h2>\r\n");
      out.write("                            <p>아래에서 원하시는 테마를 선택해주세요</p>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("                <!-- step1 form 시작점  -->\r\n");
      out.write("            <form action=\"adminCreate.pl\" method=\"post\" name=\"\">\r\n");
      out.write("                <div class=\"tab-content\">\r\n");
      out.write("                    <div class=\"tab-pane active\" id=\"tabs-1\" role=\"tabpanel\">\r\n");
      out.write("                        <div class=\"row\">\r\n");
      out.write("                            <div class=\"col-lg-4 col-md-6\">\r\n");
      out.write("                                <div class=\"listing__item\">\r\n");
      out.write("                                    <div class=\"listing__item__pic set-bg\" data-setbg=\"");
      out.print( contextPath );
      out.write("/resources/img/listing/list-1.jpg\">\r\n");
      out.write("                                        <div class=\"listing__item__pic__btns\">\r\n");
      out.write("                                        </div>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                    <div class=\"listing__item__text\">\r\n");
      out.write("                                        <div class=\"listing__item__text__inside\">\r\n");
      out.write("                                            <h4>연인과 함께</h4>\r\n");
      out.write("                                            <div class=\"listing__item__text__rating\">\r\n");
      out.write("                                                <label class=\"form-check-label\">\r\n");
      out.write("                                                    <input type=\"radio\" class=\"form-check-input\" name=\"course\"\r\n");
      out.write("                                                        id=\"optionsRadios1\" value=\"1\" checked=\"checked\">\r\n");
      out.write("                                                    2인이상\r\n");
      out.write("                                                </label>\r\n");
      out.write("            \r\n");
      out.write("                                            </div>\r\n");
      out.write("                                        </div>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <div class=\"col-lg-4 col-md-6\">\r\n");
      out.write("                                <div class=\"listing__item\">\r\n");
      out.write("                                    <div class=\"listing__item__pic set-bg\" data-setbg=\"");
      out.print( contextPath );
      out.write("/resources/img/listing/list-1.jpg\">\r\n");
      out.write("                                        <div class=\"listing__item__pic__btns\">\r\n");
      out.write("                                        </div>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                    <div class=\"listing__item__text\">\r\n");
      out.write("                                        <div class=\"listing__item__text__inside\">\r\n");
      out.write("                                            <h4>가족과 함께</h4>\r\n");
      out.write("                                            <div class=\"listing__item__text__rating\">\r\n");
      out.write("                                                <label class=\"form-check-label\">\r\n");
      out.write("                                                    <input type=\"radio\" class=\"form-check-input\" name=\"course\"\r\n");
      out.write("                                                        id=\"optionsRadios2\" value=\"2\">\r\n");
      out.write("                                                    4인이상\r\n");
      out.write("                                                </label>\r\n");
      out.write("                                            </div>\r\n");
      out.write("            \r\n");
      out.write("                                        </div>\r\n");
      out.write("            \r\n");
      out.write("                                    </div>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <div class=\"col-lg-4 col-md-6\">\r\n");
      out.write("                                <div class=\"listing__item\">\r\n");
      out.write("                                    <div class=\"listing__item__pic set-bg\" data-setbg=\"");
      out.print( contextPath );
      out.write("/resources/img/listing/list-1.jpg\">\r\n");
      out.write("                                        <div class=\"listing__item__pic__btns\">\r\n");
      out.write("                                        </div>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                    <div class=\"listing__item__text\">\r\n");
      out.write("                                        <div class=\"listing__item__text__inside\">\r\n");
      out.write("                                            <h4>친구와 함께</h4>\r\n");
      out.write("                                            <div class=\"listing__item__text__rating\">\r\n");
      out.write("                                                <label class=\"form-check-label\">\r\n");
      out.write("                                                    <input type=\"radio\" class=\"form-check-input\" name=\"course\"\r\n");
      out.write("                                                        id=\"optionsRadios3\" value=\"3\">\r\n");
      out.write("                                                    3인이상\r\n");
      out.write("                                                </label>\r\n");
      out.write("            \r\n");
      out.write("                                            </div>\r\n");
      out.write("            \r\n");
      out.write("                                        </div>\r\n");
      out.write("            \r\n");
      out.write("                                    </div>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("            \r\n");
      out.write("         \r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("                <div class=\"container\">\r\n");
      out.write("                <div class=\"row\">\r\n");
      out.write("                    <div class=\"col-lg-12\">\r\n");
      out.write("                        <div class=\"section-title\">\r\n");
      out.write("                            <hr><br>\r\n");
      out.write("                            <h2>STEP 2</h2>\r\n");
      out.write("                            <p>아래에서 원하시는 날짜와 위치를 선택해주세요</p>\r\n");
      out.write("                        \r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("\r\n");
      out.write("           \r\n");
      out.write("                    <div class=\"loca_1\">\r\n");
      out.write("                        <!-- <div class=\"dropdown\">\r\n");
      out.write("                            <h2>위치를 선택해주세요</h2>\r\n");
      out.write("                            <button class=\"btn btn-secondary dropdown-toggle\" type=\"button\" id=\"dropdownMenuButton\" data-toggle=\"dropdown\"\r\n");
      out.write("                                aria-haspopup=\"true\" aria-expanded=\"false\">클릭하셔서 위치를 선택해주세요</button>\r\n");
      out.write("                            <div class=\"dropdown-menu\" aria-labelledby=\"dropdownMenuButton\">\r\n");
      out.write("                                <a class=\"dropdown-item\" type=\"submit\">홍대</a>\r\n");
      out.write("                                <a class=\"dropdown-item\" type=\"submit\">신촌</a>\r\n");
      out.write("                                <a class=\"dropdown-item\" type=\"submit\">연남동</a>\r\n");
      out.write("                                <a class=\"dropdown-item\" type=\"submit\">연남동</a>\r\n");
      out.write("                                <a class=\"dropdown-item\" type=\"submit\">연남동</a>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div> -->\r\n");
      out.write("\r\n");
      out.write("                        <h2>위치를 선택해주세요</h2>\r\n");
      out.write("                        <select name=\"area\" onchange=\"handleOnChange(this)\">\r\n");
      out.write("                            <option value=\"1\">홍대</option>\r\n");
      out.write("                            <option value=\"2\">강남</option>\r\n");
      out.write("                        </select>\r\n");
      out.write("                        <div id='result'></div>\r\n");
      out.write("                        \r\n");
      out.write("                        </div>\r\n");
      out.write("                        \r\n");
      out.write("                        \r\n");
      out.write("                        <div class=\"date_1\" id='result'>\r\n");
      out.write("                            <h2>날짜를 선택해주세요</h2>\r\n");
      out.write("                        \r\n");
      out.write("                            <input type=\"text\" name=\"chooseDate\" id=\"startDate\">\r\n");
      out.write("                        <!-- \r\n");
      out.write("                            <button type=\"button\" class=\"btn btn-dark\">확인</button>\r\n");
      out.write("                         -->\r\n");
      out.write("                        </div>\r\n");
      out.write("                        \r\n");
      out.write("                         	<!--  혹시모르니 추천일정도 제목을 붙일 수 있게 해둘까 -->\r\n");
      out.write("                        <!-- <div class=\"title\">\r\n");
      out.write("                        	<label>추천일정 저장 제목 </label>\r\n");
      out.write("                        	<input type=\"text\" name=\"title\" >\r\n");
      out.write("                        \r\n");
      out.write("                        </div>  -->\r\n");
      out.write("             \r\n");
      out.write("                         \r\n");
      out.write("                       \r\n");
      out.write("                        \r\n");
      out.write("                        <div class=\"total_btn\" style=\"text-align: center;\">\r\n");
      out.write("                            <a href=\"");
      out.print( contextPath );
      out.write("/index.jsp\"><button type=\"button\" class=\"site-btn\">메인으로</button></a>\r\n");
      out.write("                          \r\n");
      out.write(" 					 <button type=\"submit\" value =\"전송\" class=\"site-btn\">다음으로</button>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <br>\r\n");
      out.write("                         <div style=\"text-align: center;\">\r\n");
      out.write("                          \r\n");
      out.write("                                <h4>확인을 누른후 다음으로 클릭하셔서 일정을 추천 받으세요!</h4>\r\n");
      out.write("                                <p> 인원에 따라 추가 금액이 발생 할 수 있습니다 </p>\r\n");
      out.write("                           \r\n");
      out.write("                        \r\n");
      out.write("                        </div>\r\n");
      out.write("     	</form>\r\n");
      out.write("     \r\n");
      out.write("     </section>\r\n");
      out.write("\r\n");
      out.write("   \r\n");
      out.write("\r\n");
      out.write("   \r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    ");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title></title>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    \r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("<!-- Footer Section Begin -->\r\n");
      out.write("    <footer class=\"footer\">\r\n");
      out.write("        <div class=\"container\">\r\n");
      out.write("            <div class=\"row\">\r\n");
      out.write("                <div class=\"col-lg-4 col-md-6\">\r\n");
      out.write("                    <div class=\"footer__about\">\r\n");
      out.write("                        <div class=\"footer__about__logo\">\r\n");
      out.write("                            <a href=\"");
      out.print(request.getContextPath());
      out.write("/index.jsp\"><img src=\"");
      out.print(request.getContextPath());
      out.write("/resources/img/Logo_D_1.png\" alt=\"\"></a>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <p>어디갈까 고민될 때는 어디어디!! &#128150;<br>\r\n");
      out.write("                        어디어디와 함께라면 지루한 일상도 특별하게\r\n");
      out.write("\r\n");
      out.write("                        </p>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"col-lg-6 offset-lg-2 col-md-6\">\r\n");
      out.write("                    <div class=\"footer__address\">\r\n");
      out.write("                        <ul>\r\n");
      out.write("                            <li>\r\n");
      out.write("                                <span>전화번호:</span>\r\n");
      out.write("                                <p>(+12) 345-678-910</p>\r\n");
      out.write("                            </li>\r\n");
      out.write("                            <li>\r\n");
      out.write("                                <span>이메일:</span>\r\n");
      out.write("                                <p>info.colorlib@gmail .com</p>\r\n");
      out.write("                            </li>\r\n");
      out.write("                            <li>\r\n");
      out.write("                                <span>주소:</span>\r\n");
      out.write("                                <p>서울특별시 강남구<br> 테헤란로14길 6</p>\r\n");
      out.write("                            </li>\r\n");
      out.write("                            <li>\r\n");
      out.write("                                <span>Connect Us:</span>\r\n");
      out.write("                                <div class=\"footer__social\">\r\n");
      out.write("                                    <a href=\"#\"><i class=\"fa fa-facebook\"></i></a>\r\n");
      out.write("                                    <a href=\"#\"><i class=\"fa fa-instagram\"></i></a>\r\n");
      out.write("                                    <a href=\"#\"><i class=\"fa fa-twitter\"></i></a>\r\n");
      out.write("                                    <a href=\"#\"><i class=\"fa fa-skype\"></i></a>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </li>\r\n");
      out.write("                        </ul>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("              \r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"row\">\r\n");
      out.write("                <div class=\"col-lg-12\">\r\n");
      out.write("                    <div class=\"footer__copyright\">\r\n");
      out.write("                        <div class=\"footer__copyright__text\"><p><!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->\r\n");
      out.write("  Copyright &copy;<script>document.write(new Date().getFullYear());</script> img by pngtree, Korea tourism oranization <i class=\"fa fa-heart\" aria-hidden=\"true\"></i> by <a href=\"https://colorlib.com\" target=\"_blank\">Colorlib</a>\r\n");
      out.write("  <!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. --></p>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"footer__copyright__links\">\r\n");
      out.write("                            <a href=\"#\">서비스 소개</a>\r\n");
      out.write("                            <a href=\"#\">이용약관</a>\r\n");
      out.write("                            <a href=\"#\">개인정보처리방침</a>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </footer>\r\n");
      out.write("    <!-- Footer Section End -->\r\n");
      out.write("\r\n");
      out.write("  \r\n");
      out.write(" \r\n");
      out.write(" \r\n");
      out.write("    \r\n");
      out.write("   \r\n");
      out.write("    \r\n");
      out.write("</body>\r\n");
      out.write("</html>");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    \r\n");
      out.write("    <script src=\"");
      out.print( contextPath );
      out.write("/resources/js/main.js\"></script>\r\n");
      out.write("</body>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!-- 자바스크립트 함수부분  -->\r\n");
      out.write("		\r\n");
      out.write("		<script>\r\n");
      out.write("		\r\n");
      out.write("		    // 위치 선택 출력 \r\n");
      out.write("		    function handleOnChange(e) {\r\n");
      out.write("		        // 선택된 데이터 가져오기\r\n");
      out.write("		        const value = e.value;\r\n");
      out.write("		\r\n");
      out.write("		        // 데이터 출력\r\n");
      out.write("		        document.getElementById('result').innerText\r\n");
      out.write("		            = value;\r\n");
      out.write("		    }\r\n");
      out.write("		</script>\r\n");
      out.write("		\r\n");
      out.write("		<script> // 달력 날짜 선택 \r\n");
      out.write("		 \r\n");
      out.write("			$(function() {\r\n");
      out.write("				$('#startDate').datepicker({\r\n");
      out.write("\r\n");
      out.write("				})\r\n");
      out.write("\r\n");
      out.write("			})\r\n");
      out.write("		</script>\r\n");
      out.write("		\r\n");
      out.write("<script>\r\n");
      out.write("    $(function () {\r\n");
      out.write("        var $header = $('header'); //헤더를 변수에 넣기\r\n");
      out.write("        var $page = $('.page-start'); //색상이 변할 부분\r\n");
      out.write("        var $window = $(window);\r\n");
      out.write("        var pageOffsetTop = $page.offset().top;//색상 변할 부분의 top값 구하기\r\n");
      out.write("\r\n");
      out.write("        $window.resize(function () { //반응형을 대비하여 리사이즈시 top값을 다시 계산\r\n");
      out.write("            pageOffsetTop = $page.offset().top;\r\n");
      out.write("        });\r\n");
      out.write("\r\n");
      out.write("        $window.on('scroll', function () { //스크롤시\r\n");
      out.write("            var scrolled = $window.scrollTop() >= pageOffsetTop; //스크롤된 상태; true or false\r\n");
      out.write("            $header.toggleClass('down', scrolled); //클래스 토글\r\n");
      out.write("        });\r\n");
      out.write("    });\r\n");
      out.write("\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
